i18n/ru-RU.json
=> Russian translation fixes

submodules/wizard/wizard.js
Also avoid to do unnecessary requests.
=> MACT-14: Fix account data inconsistencies at wizard

submodules/wizard/wizard.js
Also avoid to do unnecessary requests.
=> [4.3] MACT-14: Fix account data inconsistencies at wizard

submodules/wizard/views/step-review.html, submodules/wizard/wizard.js, submodules/wizard/wizard.scss, tests/wizard.side
* Tweak styles to match Abstract's mockups.
* Hide add app button if there are no more apps available to select.
=> MACT-33: Improve app restrictions UX

i18n/en-US.json, submodules/wizard/views/step-review.html, submodules/wizard/views/step-usageAndCallRestrictions.html, submodules/wizard/wizard.scss, tests/wizard.side
Also update its label in the review step of the wizard.
=> MACT-24: Use checkbox for per-minute calls option

submodules/wizard/views/step-generalSettings.html, submodules/wizard/wizard.js, submodules/wizard/wizard.scss, tests/wizard.side
=> MACT-36: Use country selector at wizard step

submodules/wizard/wizard.js, views/edit.html
...Add validation on account edit to be aligned with account creation
=> MACT-41: Add postal code validation

submodules/wizard/wizard.js, views/edit.html
...Add validation on account edit to be aligned with account creation
=> [4.3] MACT-41: Add postal code validation

submodules/wizard/views/adminForm.html, submodules/wizard/views/step-generalSettings.html, submodules/wizard/wizard.js
=> MACT-49: Check admin e-mails uniqueness at wizard

submodules/wizard/views/step-appRestrictions.html, submodules/wizard/wizard.js
=> MACT-50: Fix edit links on wizard review step

submodules/wizard/wizard.js
=> MACT-46: Set parent's tz as default for new account

submodules/wizard/wizard.js
=> MACT-48: Use parent values for ctry/lang defaults

i18n/en-US.json, submodules/wizard/wizard.js
=> MACT-54: Add missing Control Center features to wizard

submodules/wizard/wizard.js
=> MACT-64: Save account realm and omit empty values

i18n/en-US.json
=> MACT-56: Fix typo at wizard's admins section

submodules/wizard/wizard.js
=> MACT-49: Make admin email checks case insensitive

submodules/serviceItemsListing/serviceItemsListing.js
=> MACT-57: Start plan items qty ranges at zero

submodules/wizard/wizard.js
=> MACT-66: Use async callback to render wizard steps

submodules/wizard/wizard.js
=> MACT-49: Fix admin users validation at wizard

i18n/en-US.json
=> MACT-62: Change restriction tab label at account edit

app.js, submodules/wizard/wizard.js
=> MACT-59: Load parent list after account creation

submodules/serviceItemsListing/serviceItemsListing.js
Fixes https://2600hz-commercial.atlassian.net/browse/MACT-57?focusedCommentId=11964
4.3 -> #119
=> MACT-57: Fix merged plan item sorting

submodules/wizard/wizard.js
=> MACT-69: Get account representatives from reseller

submodules/serviceItemsListing/serviceItemsListing.js, submodules/wizard/wizard.js
=> MACT-68: Get wizard data lists from reseller

submodules/wizard/wizard.js
=> MACT-70: Get options from parent account when reseller is unavailable

submodules/wizard/wizard.js
=> MACT-49: Re-validate e-mails on admin delete

submodules/wizard/wizard.js
=> MACT-85: Show sales rep section at wizard

submodules/wizard/views/step-creditBalanceAndFeatures.html, submodules/wizard/views/step-review.html, submodules/wizard/views/step-usageAndCallRestrictions.html, submodules/wizard/wizard.js
=> MACT-87: Ignore limits & credit at wizard if non master/reseller

submodules/wizard/views/adminForm.html, submodules/wizard/wizard.js, submodules/wizard/wizard.scss
=> MACT-61: Add strength indicator to admin password

app.js, i18n/en-US.json, views/edit.html
=> MACT-92: Expose sales info management component
